function Xdot = model(time, X, param, Lvect)
bP = param(1); bI = param(2); bA = param(3);
th = param(4);
dE = param(5); dP = param(6); 
sig = param(7); 
nI = param(8); nA = param(9);
z = param(10);
gI = param(11); gA = param(12); gH = param(13); gQ = param(14);
aI = param(15); aH = param(16); aU = 4*aH;
Hbed = param(17);
X0 = param(20:end);
S = X(1);  
E = X(2);  
P = X(3);  
I = X(4);  
A = X(5);  
H = X(6);  
Q = X(7);  
R1 = X(8); 
R2 = X(9); 
D = X(10); 
N = X(11); 
Lvect = Lvect';
L = Lvect(1,fix(time)+1);
l = ((1-th*L)*(bP*P + bI*I + bA*A))/(S + E + P + I + A + R1 + R2);
U = max(0, H-Hbed);
Xdot = zeros(length(X0),1);
Xdot(1) = - l*S*(1 - th*L);
Xdot(2) = l*S*(1 - th*L) - dE*E;
Xdot(3) = dE*E - dP*P; 
Xdot(4) = sig*dP*P - (nI + gI + aI)*I;
Xdot(5) = (1 - sig)*dP*P - gA*A - nA*A; 
Xdot(6) = (1 - z)*nI*I - (gH + aH)*min(H,Hbed) - aU*U;
Xdot(7) = z*nI*I + nA*A - gQ*Q;
Xdot(8) = gI*I + gH*H + gQ*Q; 
Xdot(9) = gA*A;
Xdot(10) = aI*I + aH*min(H,Hbed) + aU*U;
Xdot(11) = -(aI*I + aH*min(H,Hbed) + aU*U);
end